<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<?php 
          $session = new UserSession();
            $result = $session->getUserName();
            $resultId = $session->getUserId();
       ?>

<!-- En-tête commune -->
<header>
    <h1>
        <?php if ($resultId == 1): ?>
          <a href="<?= $requestUrl ?>/admin">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
          </a>
        <?php else: ?>
          <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
          </a>
        <?php endif; ?>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
        
        <li>
          <?php echo $result; ?>
        </li>
        <li>
           <a href="<?php echo $requestUrl ?>" class="button">Home</a>
       </li>
       
       <?php if(!$result): ?>
       <li>
            <a href="<?php echo $requestUrl ?>/inscription" class="button button-primary">Inscription</a>
       </li>
       <li>
           <a href="<?= $requestUrl ?>/connexion" class="button ">Connexion</a>
       </li>
     <?php else: ?>
      <li>
          <a href="<?php echo $requestUrl ?>/order?idUser=<?php echo $resultId; ?>" class="button">Commander</a>
       </li>
       <li>
           <a href="<?= $requestUrl ?>/deconnexion" class="button buton-primary">Deconnexion</a>
       </li>
     <?php endif; ?>
       
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/jquery.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/orderlines.js"></script>
</body>
</html>